name: Test git action when PR to dev

on:
  push:
    branches:
      - dev
    pull_request:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run simple test
        run: echo "✅ GitHub Action triggered successfully on branch dev"

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with: 
          args: > 
          -Dsonar.projectKey=tranduynhoa94_devops-practice-git-trigger
          -Dsonar.organization=tranduynhoa94 
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
          -Dsonar.pullrequest.branch=${{ github.head_ref }} 
          -Dsonar.pullrequest.base=${{ github.base_ref }}
